units:
  - {slug: namespace, file: namespace.yaml}
  - {slug: controller, file: controller.yaml}
  - {slug: ingress-class, file: ingress-class.yaml}
  - {slug: middleware, file: middleware.yaml}
values:
  version: v3.2.1
perClass:
  dev:
    - {function: set-replicas, args: ["{{.Class.Replicas}}"], where: "Slug = 'controller'"}
    - {function: set-env-var, args: ["*", "TRAEFIK_LOG_LEVEL", "{{.Class.LogLevel}}"], where: "Slug = 'controller'"}
  test:
    - {function: set-replicas, args: ["{{.Class.Replicas}}"], where: "Slug = 'controller'"}
    - {function: set-env-var, args: ["*", "TRAEFIK_LOG_LEVEL", "{{.Class.LogLevel}}"], where: "Slug = 'controller'"}
  uat:
    - {function: set-replicas, args: ["{{.Class.Replicas}}"], where: "Slug = 'controller'"}
    - {function: set-env-var, args: ["*", "TRAEFIK_LOG_LEVEL", "{{.Class.LogLevel}}"], where: "Slug = 'controller'"}
  prod:
    - {function: set-replicas, args: ["{{.Class.Replicas}}"], where: "Slug = 'controller'"}
    - {function: set-env-var, args: ["*", "TRAEFIK_LOG_LEVEL", "{{.Class.LogLevel}}"], where: "Slug = 'controller'"}
