units:
  - {slug: namespace, file: namespace.yaml}
  - {slug: scorer, file: scorer.yaml}
values:
  version: 2.2.0
perClass:
  dev:
    - {function: set-replicas, args: ["{{.Class.Replicas}}"], where: "Slug = 'scorer'"}
    - {function: set-env-var, args: ["*", "LOG_LEVEL", "{{.Class.LogLevel}}"], where: "Slug = 'scorer'"}
  test:
    - {function: set-replicas, args: ["{{.Class.Replicas}}"], where: "Slug = 'scorer'"}
    - {function: set-env-var, args: ["*", "LOG_LEVEL", "{{.Class.LogLevel}}"], where: "Slug = 'scorer'"}
  uat:
    - {function: set-replicas, args: ["{{.Class.Replicas}}"], where: "Slug = 'scorer'"}
    - {function: set-env-var, args: ["*", "LOG_LEVEL", "{{.Class.LogLevel}}"], where: "Slug = 'scorer'"}
  prod:
    - {function: set-replicas, args: ["{{.Class.Replicas}}"], where: "Slug = 'scorer'"}
    - {function: set-env-var, args: ["*", "LOG_LEVEL", "{{.Class.LogLevel}}"], where: "Slug = 'scorer'"}
perRegion:
  - {function: set-env-var, args: ["*", "AWS_REGION", "{{.Region.ProviderRegion}}"], where: "Slug = 'scorer'"}
